/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package socourse;

import java.awt.Color;
import java.util.ArrayList;
import javax.swing.JPanel;

/**
 *
 * @author Satria Aji Putra
 */
public class MainFrame extends javax.swing.JFrame {

    private static String username;
    private ArrayList<JPanel> menus = new ArrayList<>();
    private Color primaryColor = new Color(0,102,255);
    private Color primaryColorHover = new Color(108,163,247);

    /**
     * Creates new form MainFrame
     */
    public MainFrame(String username) {
        initComponents();
        this.username = username;
        labelUsername.setText(username);
        setMenus();
        initHome();
    }
    
    private void resetActiveMenu() {
        menus.forEach(menu -> menu.setBackground(primaryColor));
    }
    
    private void setActiveMenu(JPanel menu) {
        resetActiveMenu();
        menu.setBackground(primaryColorHover);
    }
    
    private void setMenus() {
        menus.add(btnHome);
        menus.add(btnCourse);
        menus.add(btnExercise);
        menus.add(btnResources);
        menus.add(btnAbout);
        menus.add(btnSignOut);
    }
    
    private void initHome() {
        setActiveMenu(btnHome);
        setActivePanel(panelContent, panelHome);
        labelPageTitle.setText("Home");
    }
    
    private void setActivePanel(JPanel parentPanel, JPanel panel) {
        parentPanel.removeAll();
        parentPanel.repaint();
        parentPanel.revalidate();
        parentPanel.add(panel);
        parentPanel.repaint();
        parentPanel.revalidate();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnHome = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        btnCourse = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        btnExercise = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        btnResources = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        btnAbout = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        btnSignOut = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        labelPageTitle = new javax.swing.JLabel();
        labelUsername = new javax.swing.JLabel();
        panelContent = new javax.swing.JPanel();
        panelHome = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        panelCourse = new javax.swing.JPanel();
        jPanel12 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jPanel13 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        panelExercise = new javax.swing.JPanel();
        jPanel14 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jPanel15 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        panelResources = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(800, 60));
        setMinimumSize(new java.awt.Dimension(800, 600));

        jPanel1.setBackground(new java.awt.Color(0, 102, 255));
        jPanel1.setMaximumSize(new java.awt.Dimension(180, 600));
        jPanel1.setMinimumSize(new java.awt.Dimension(180, 600));
        jPanel1.setPreferredSize(new java.awt.Dimension(180, 600));

        jLabel1.setFont(new java.awt.Font("Lato", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Soucourse");

        btnHome.setBackground(new java.awt.Color(0, 102, 255));
        btnHome.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnHome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnHomeMouseClicked(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Lato", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/images/icon_home.png"))); // NOI18N
        jLabel2.setText("Home");
        jLabel2.setIconTextGap(20);

        org.jdesktop.layout.GroupLayout btnHomeLayout = new org.jdesktop.layout.GroupLayout(btnHome);
        btnHome.setLayout(btnHomeLayout);
        btnHomeLayout.setHorizontalGroup(
            btnHomeLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(btnHomeLayout.createSequentialGroup()
                .add(30, 30, 30)
                .add(jLabel2)
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        btnHomeLayout.setVerticalGroup(
            btnHomeLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(btnHomeLayout.createSequentialGroup()
                .add(18, 18, 18)
                .add(jLabel2)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        btnCourse.setBackground(new java.awt.Color(0, 102, 255));
        btnCourse.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCourse.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCourseMouseClicked(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Lato", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/images/icon_book.png"))); // NOI18N
        jLabel3.setText("Course");
        jLabel3.setIconTextGap(20);

        org.jdesktop.layout.GroupLayout btnCourseLayout = new org.jdesktop.layout.GroupLayout(btnCourse);
        btnCourse.setLayout(btnCourseLayout);
        btnCourseLayout.setHorizontalGroup(
            btnCourseLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(btnCourseLayout.createSequentialGroup()
                .add(30, 30, 30)
                .add(jLabel3)
                .addContainerGap(61, Short.MAX_VALUE))
        );
        btnCourseLayout.setVerticalGroup(
            btnCourseLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(btnCourseLayout.createSequentialGroup()
                .add(18, 18, 18)
                .add(jLabel3)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        btnExercise.setBackground(new java.awt.Color(0, 102, 255));
        btnExercise.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnExercise.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnExerciseMouseClicked(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Lato", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/images/icon_code.png"))); // NOI18N
        jLabel4.setText("Exercise");
        jLabel4.setIconTextGap(20);

        org.jdesktop.layout.GroupLayout btnExerciseLayout = new org.jdesktop.layout.GroupLayout(btnExercise);
        btnExercise.setLayout(btnExerciseLayout);
        btnExerciseLayout.setHorizontalGroup(
            btnExerciseLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(btnExerciseLayout.createSequentialGroup()
                .add(30, 30, 30)
                .add(jLabel4)
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        btnExerciseLayout.setVerticalGroup(
            btnExerciseLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(btnExerciseLayout.createSequentialGroup()
                .add(18, 18, 18)
                .add(jLabel4)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        btnResources.setBackground(new java.awt.Color(0, 102, 255));
        btnResources.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnResources.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnResourcesMouseClicked(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Lato", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/images/icon_archive.png"))); // NOI18N
        jLabel5.setText("Resources");
        jLabel5.setIconTextGap(20);

        org.jdesktop.layout.GroupLayout btnResourcesLayout = new org.jdesktop.layout.GroupLayout(btnResources);
        btnResources.setLayout(btnResourcesLayout);
        btnResourcesLayout.setHorizontalGroup(
            btnResourcesLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(btnResourcesLayout.createSequentialGroup()
                .add(30, 30, 30)
                .add(jLabel5)
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        btnResourcesLayout.setVerticalGroup(
            btnResourcesLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(btnResourcesLayout.createSequentialGroup()
                .add(18, 18, 18)
                .add(jLabel5)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        btnAbout.setBackground(new java.awt.Color(0, 102, 255));
        btnAbout.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAbout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAboutMouseClicked(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Lato", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/images/icon_about.png"))); // NOI18N
        jLabel6.setText("About");
        jLabel6.setIconTextGap(20);

        org.jdesktop.layout.GroupLayout btnAboutLayout = new org.jdesktop.layout.GroupLayout(btnAbout);
        btnAbout.setLayout(btnAboutLayout);
        btnAboutLayout.setHorizontalGroup(
            btnAboutLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(btnAboutLayout.createSequentialGroup()
                .add(30, 30, 30)
                .add(jLabel6)
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        btnAboutLayout.setVerticalGroup(
            btnAboutLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(btnAboutLayout.createSequentialGroup()
                .add(18, 18, 18)
                .add(jLabel6)
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnSignOut.setBackground(new java.awt.Color(0, 102, 255));
        btnSignOut.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSignOut.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSignOutMouseClicked(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Lato", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/images/icon_logout.png"))); // NOI18N
        jLabel7.setText("Sign Out");
        jLabel7.setIconTextGap(20);

        org.jdesktop.layout.GroupLayout btnSignOutLayout = new org.jdesktop.layout.GroupLayout(btnSignOut);
        btnSignOut.setLayout(btnSignOutLayout);
        btnSignOutLayout.setHorizontalGroup(
            btnSignOutLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(btnSignOutLayout.createSequentialGroup()
                .add(30, 30, 30)
                .add(jLabel7)
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        btnSignOutLayout.setVerticalGroup(
            btnSignOutLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(btnSignOutLayout.createSequentialGroup()
                .add(18, 18, 18)
                .add(jLabel7)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        org.jdesktop.layout.GroupLayout jPanel1Layout = new org.jdesktop.layout.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .add(30, 30, 30)
                .add(jLabel1)
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .add(btnHome, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .add(btnCourse, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .add(btnExercise, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .add(btnResources, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .add(btnAbout, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .add(btnSignOut, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .add(30, 30, 30)
                .add(jLabel1)
                .add(45, 45, 45)
                .add(btnHome, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(0, 0, 0)
                .add(btnCourse, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(0, 0, 0)
                .add(btnExercise, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(0, 0, 0)
                .add(btnResources, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(0, 0, 0)
                .add(btnAbout, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(0, 0, 0)
                .add(btnSignOut, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(203, 227, 252));

        jPanel9.setBackground(new java.awt.Color(255, 255, 255));
        jPanel9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        jPanel9.setMaximumSize(new java.awt.Dimension(555, 60));
        jPanel9.setMinimumSize(new java.awt.Dimension(555, 60));
        jPanel9.setPreferredSize(new java.awt.Dimension(555, 60));

        labelPageTitle.setFont(new java.awt.Font("Lato", 1, 18)); // NOI18N
        labelPageTitle.setText("Home");

        labelUsername.setFont(new java.awt.Font("Lato", 1, 14)); // NOI18N
        labelUsername.setForeground(new java.awt.Color(51, 51, 51));
        labelUsername.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/images/icon_user.png"))); // NOI18N
        labelUsername.setText("username");

        org.jdesktop.layout.GroupLayout jPanel9Layout = new org.jdesktop.layout.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel9Layout.createSequentialGroup()
                .add(30, 30, 30)
                .add(labelPageTitle)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .add(labelUsername)
                .add(30, 30, 30))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel9Layout.createSequentialGroup()
                .add(18, 18, 18)
                .add(jPanel9Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(labelPageTitle)
                    .add(labelUsername))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        panelContent.setBackground(new java.awt.Color(255, 255, 255));
        panelContent.setLayout(new java.awt.CardLayout());

        panelHome.setBackground(new java.awt.Color(255, 255, 255));

        jLabel8.setFont(new java.awt.Font("Lato", 1, 14)); // NOI18N
        jLabel8.setText("Course");

        jLabel9.setFont(new java.awt.Font("Lato", 1, 36)); // NOI18N
        jLabel9.setText("11");

        org.jdesktop.layout.GroupLayout jPanel10Layout = new org.jdesktop.layout.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel10Layout.createSequentialGroup()
                .add(15, 15, 15)
                .add(jPanel10Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jLabel8)
                    .add(jLabel9))
                .addContainerGap(133, Short.MAX_VALUE))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .add(jLabel8)
                .add(15, 15, 15)
                .add(jLabel9)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        jLabel10.setFont(new java.awt.Font("Lato", 1, 14)); // NOI18N
        jLabel10.setText("Exp");

        jLabel11.setFont(new java.awt.Font("Lato", 1, 36)); // NOI18N
        jLabel11.setText("21421");

        org.jdesktop.layout.GroupLayout jPanel11Layout = new org.jdesktop.layout.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel11Layout.createSequentialGroup()
                .add(15, 15, 15)
                .add(jPanel11Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jLabel10)
                    .add(jLabel11))
                .addContainerGap(72, Short.MAX_VALUE))
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .add(jLabel10)
                .add(15, 15, 15)
                .add(jLabel11)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        org.jdesktop.layout.GroupLayout panelHomeLayout = new org.jdesktop.layout.GroupLayout(panelHome);
        panelHome.setLayout(panelHomeLayout);
        panelHomeLayout.setHorizontalGroup(
            panelHomeLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(panelHomeLayout.createSequentialGroup()
                .add(31, 31, 31)
                .add(jPanel10, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(18, 18, 18)
                .add(jPanel11, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(212, Short.MAX_VALUE))
        );
        panelHomeLayout.setVerticalGroup(
            panelHomeLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(panelHomeLayout.createSequentialGroup()
                .add(31, 31, 31)
                .add(panelHomeLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jPanel11, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jPanel10, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(331, Short.MAX_VALUE))
        );

        panelContent.add(panelHome, "card2");

        panelCourse.setBackground(new java.awt.Color(255, 255, 255));

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/images/coding.png"))); // NOI18N

        jLabel13.setFont(new java.awt.Font("Lato", 1, 14)); // NOI18N
        jLabel13.setText("Java Course");

        org.jdesktop.layout.GroupLayout jPanel12Layout = new org.jdesktop.layout.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel12Layout.createSequentialGroup()
                .add(15, 15, 15)
                .add(jPanel12Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jLabel13)
                    .add(jLabel12))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel12Layout.createSequentialGroup()
                .add(15, 15, 15)
                .add(jLabel12)
                .add(15, 15, 15)
                .add(jLabel13)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/images/coding.png"))); // NOI18N

        jLabel15.setFont(new java.awt.Font("Lato", 1, 14)); // NOI18N
        jLabel15.setText("Java Course");

        org.jdesktop.layout.GroupLayout jPanel13Layout = new org.jdesktop.layout.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel13Layout.createSequentialGroup()
                .add(15, 15, 15)
                .add(jPanel13Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jLabel15)
                    .add(jLabel14))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel13Layout.createSequentialGroup()
                .add(15, 15, 15)
                .add(jLabel14)
                .add(15, 15, 15)
                .add(jLabel15)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        org.jdesktop.layout.GroupLayout panelCourseLayout = new org.jdesktop.layout.GroupLayout(panelCourse);
        panelCourse.setLayout(panelCourseLayout);
        panelCourseLayout.setHorizontalGroup(
            panelCourseLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(panelCourseLayout.createSequentialGroup()
                .add(85, 85, 85)
                .add(jPanel12, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(18, 18, 18)
                .add(jPanel13, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(92, Short.MAX_VALUE))
        );
        panelCourseLayout.setVerticalGroup(
            panelCourseLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(panelCourseLayout.createSequentialGroup()
                .add(29, 29, 29)
                .add(panelCourseLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(jPanel13, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jPanel12, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(233, Short.MAX_VALUE))
        );

        panelContent.add(panelCourse, "card3");

        panelExercise.setBackground(new java.awt.Color(255, 255, 255));

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/images/coding.png"))); // NOI18N

        jLabel17.setFont(new java.awt.Font("Lato", 1, 14)); // NOI18N
        jLabel17.setText("Java Course");

        org.jdesktop.layout.GroupLayout jPanel14Layout = new org.jdesktop.layout.GroupLayout(jPanel14);
        jPanel14.setLayout(jPanel14Layout);
        jPanel14Layout.setHorizontalGroup(
            jPanel14Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel14Layout.createSequentialGroup()
                .add(15, 15, 15)
                .add(jPanel14Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jLabel17)
                    .add(jLabel16))
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel14Layout.setVerticalGroup(
            jPanel14Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel14Layout.createSequentialGroup()
                .add(15, 15, 15)
                .add(jLabel16)
                .add(15, 15, 15)
                .add(jLabel17)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/images/coding.png"))); // NOI18N

        jLabel19.setFont(new java.awt.Font("Lato", 1, 14)); // NOI18N
        jLabel19.setText("Java Course");

        org.jdesktop.layout.GroupLayout jPanel15Layout = new org.jdesktop.layout.GroupLayout(jPanel15);
        jPanel15.setLayout(jPanel15Layout);
        jPanel15Layout.setHorizontalGroup(
            jPanel15Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel15Layout.createSequentialGroup()
                .add(15, 15, 15)
                .add(jPanel15Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jLabel19)
                    .add(jLabel18))
                .addContainerGap(371, Short.MAX_VALUE))
        );
        jPanel15Layout.setVerticalGroup(
            jPanel15Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel15Layout.createSequentialGroup()
                .add(15, 15, 15)
                .add(jLabel18)
                .add(15, 15, 15)
                .add(jLabel19)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        org.jdesktop.layout.GroupLayout panelExerciseLayout = new org.jdesktop.layout.GroupLayout(panelExercise);
        panelExercise.setLayout(panelExerciseLayout);
        panelExerciseLayout.setHorizontalGroup(
            panelExerciseLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(panelExerciseLayout.createSequentialGroup()
                .add(23, 23, 23)
                .add(panelExerciseLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                    .add(jPanel15, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(jPanel14, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(46, Short.MAX_VALUE))
        );
        panelExerciseLayout.setVerticalGroup(
            panelExerciseLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(panelExerciseLayout.createSequentialGroup()
                .add(24, 24, 24)
                .add(jPanel14, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(15, 15, 15)
                .add(jPanel15, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        panelContent.add(panelExercise, "card4");

        panelResources.setBackground(new java.awt.Color(255, 255, 255));

        jTable1.setFont(new java.awt.Font("Lato", 0, 14)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"java_course", "zip", "20 KB", "Download"},
                {"responsive_view", "rar", "30 KB", "Download"}
            },
            new String [] {
                "Name", "Type", "Size", "Action"
            }
        ));
        jTable1.setRowHeight(30);
        jScrollPane1.setViewportView(jTable1);

        org.jdesktop.layout.GroupLayout panelResourcesLayout = new org.jdesktop.layout.GroupLayout(panelResources);
        panelResources.setLayout(panelResourcesLayout);
        panelResourcesLayout.setHorizontalGroup(
            panelResourcesLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(panelResourcesLayout.createSequentialGroup()
                .add(89, 89, 89)
                .add(jScrollPane1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(104, Short.MAX_VALUE))
        );
        panelResourcesLayout.setVerticalGroup(
            panelResourcesLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(panelResourcesLayout.createSequentialGroup()
                .add(50, 50, 50)
                .add(jScrollPane1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 144, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(270, Short.MAX_VALUE))
        );

        panelContent.add(panelResources, "card5");

        org.jdesktop.layout.GroupLayout jPanel2Layout = new org.jdesktop.layout.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel2Layout.createSequentialGroup()
                .add(30, 30, 30)
                .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                    .add(panelContent, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(jPanel9, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 645, Short.MAX_VALUE))
                .addContainerGap(35, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel2Layout.createSequentialGroup()
                .add(30, 30, 30)
                .add(jPanel9, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(18, 18, 18)
                .add(panelContent, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 464, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(28, Short.MAX_VALUE))
        );

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(jPanel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(0, 0, 0)
                .add(jPanel2, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .add(jPanel2, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnHomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHomeMouseClicked
        labelPageTitle.setText("Home");
        setActiveMenu(btnHome);
        setActivePanel(panelContent, panelHome);
    }//GEN-LAST:event_btnHomeMouseClicked

    private void btnCourseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCourseMouseClicked
        labelPageTitle.setText("Course");
        setActiveMenu(btnCourse);
        setActivePanel(panelContent, panelCourse);
    }//GEN-LAST:event_btnCourseMouseClicked

    private void btnExerciseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnExerciseMouseClicked
        labelPageTitle.setText("Exercise");
        setActiveMenu(btnExercise);
        setActivePanel(panelContent, panelExercise);
    }//GEN-LAST:event_btnExerciseMouseClicked

    private void btnResourcesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnResourcesMouseClicked
        labelPageTitle.setText("Resources");
        setActiveMenu(btnResources);
        setActivePanel(panelContent, panelResources);
    }//GEN-LAST:event_btnResourcesMouseClicked

    private void btnAboutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAboutMouseClicked
        setActiveMenu(btnAbout);
        AboutFrame aboutFrame = new AboutFrame();
        aboutFrame.setVisible(true);
    }//GEN-LAST:event_btnAboutMouseClicked

    private void btnSignOutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSignOutMouseClicked
        RegisterFrame registerFrame = new RegisterFrame();
        registerFrame.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnSignOutMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame(username).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel btnAbout;
    private javax.swing.JPanel btnCourse;
    private javax.swing.JPanel btnExercise;
    private javax.swing.JPanel btnHome;
    private javax.swing.JPanel btnResources;
    private javax.swing.JPanel btnSignOut;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel labelPageTitle;
    private javax.swing.JLabel labelUsername;
    private javax.swing.JPanel panelContent;
    private javax.swing.JPanel panelCourse;
    private javax.swing.JPanel panelExercise;
    private javax.swing.JPanel panelHome;
    private javax.swing.JPanel panelResources;
    // End of variables declaration//GEN-END:variables
}
